[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd flask_api && pip install -r requirements.txt"]

[start]
cmd = "cd flask_api && gunicorn app:app --bind 0.0.0.0:${PORT:-8080} --timeout 120"
